#!/bin/bash

#*
#*  The MIT License
#* 
#*  Copyright 2012 Georgios Migdos <cyberpython@gmail.com>.
#* 
#*  Permission is hereby granted, free of charge, to any person obtaining a copy
#*  of this software and associated documentation files (the "Software"), to deal
#*  in the Software without restriction, including without limitation the rights
#*  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#*  copies of the Software, and to permit persons to whom the Software is
#*  furnished to do so, subject to the following conditions:
#* 
#*  The above copyright notice and this permission notice shall be included in
#*  all copies or substantial portions of the Software.
#* 
#*  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#*  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#*  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#*  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#*  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#*  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
#*  THE SOFTWARE.
#*

DIR=$(cd $(dirname "$0"); pwd)
if [ -f lingua.desktop ]
then
    rm lingua.desktop
fi
touch lingua.desktop
echo "[Desktop Entry]" | cat >> lingua.desktop
echo "Encoding=UTF-8" | cat >> lingua.desktop
echo "Name=Lingua" | cat >> lingua.desktop
echo "GenericName=Περιβάλλον Ανάπτυξης Για Τη ΓΛΩΣΣΑ" | cat >> lingua.desktop
echo "Comment=Γράψτε και εκτελέστε προγράμματα στη ΓΛΩΣΣΑ" | cat >> lingua.desktop
echo "Terminal=false" | cat >> lingua.desktop
echo "Type=Application" | cat >> lingua.desktop
echo "StartupNotify=true" | cat >> lingua.desktop
echo "MimeType=text/glossa;" | cat >> lingua.desktop
echo "Exec=java -jar $DIR/lingua.jar" | cat >> lingua.desktop
echo "Icon=$DIR/lingua-icon.svg" | cat >> lingua.desktop
chmod +x lingua.desktop

mkdir ~/.local
mkdir ~/.local/share
mkdir ~/.local/share/gtksourceview-3.0
mkdir ~/.local/share/gtksourceview-3.0/styles
mkdir ~/.local/share/gtksourceview-3.0/language-specs

if [ ! -f ~/.local/share/gtksourceview-3.0/styles/glossa.xml ]
then
    mv glossa.xml ~/.local/share/gtksourceview-3.0/styles/glossa.xml
fi

if [ ! -f ~/.local/share/gtksourceview-3.0/language-specs/glossa.lang ]
then
    mv glossa.lang ~/.local/share/gtksourceview-3.0/language-specs/glossa.lang
fi

