#!/bin/bash

# Usage : ./build-binary <version>
#   e.g.: ./build-binary 0.0.2

#*
#*  The MIT License
#* 
#*  Copyright 2012 Georgios Migdos <cyberpython@gmail.com>.
#* 
#*  Permission is hereby granted, free of charge, to any person obtaining a copy
#*  of this software and associated documentation files (the "Software"), to deal
#*  in the Software without restriction, including without limitation the rights
#*  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#*  copies of the Software, and to permit persons to whom the Software is
#*  furnished to do so, subject to the following conditions:
#* 
#*  The above copyright notice and this permission notice shall be included in
#*  all copies or substantial portions of the Software.
#* 
#*  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#*  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#*  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#*  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#*  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#*  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
#*  THE SOFTWARE.
#*

TARGET_DIR="lingua"

if [ -d binaries/$TARGET_DIR ]
then
    rm -rf binaries/$TARGET_DIR
fi

mkdir -p binaries/$TARGET_DIR
cp -R dist/* binaries/$TARGET_DIR

cd binaries

if [ -f lingua-$1-i386.zip ]
then
    rm -f lingua-$1-i386.zip
fi

zip -r lingua-$1-i386.zip $TARGET_DIR

rm -rf $TARGET_DIR

if [ -f lingua-i386.zip ]
then
    rm -f lingua-i386.zip
fi

cp lingua-$1-i386.zip lingua-i386.zip


cd ../

