#!/bin/bash

#*
#*  The MIT License
#* 
#*  Copyright 2012 Georgios Migdos <cyberpython@gmail.com>.
#* 
#*  Permission is hereby granted, free of charge, to any person obtaining a copy
#*  of this software and associated documentation files (the "Software"), to deal
#*  in the Software without restriction, including without limitation the rights
#*  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#*  copies of the Software, and to permit persons to whom the Software is
#*  furnished to do so, subject to the following conditions:
#* 
#*  The above copyright notice and this permission notice shall be included in
#*  all copies or substantial portions of the Software.
#* 
#*  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#*  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#*  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#*  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#*  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#*  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
#*  THE SOFTWARE.
#*

git clone git://github.com/cyberpython/java-gnome.git

cd java-gnome

./configure

make

cd ../

git clone git://github.com/cyberpython/glossa-interpreter.git

cd glossa-interpreter

ant clean jar

cd ../

mkdir -p lib

cp java-gnome/tmp/gtk-4.1.jar lib/gtk-4.1.jar
cp java-gnome/tmp/libgtkjni-4.1.2-dev.so lib/libgtkjni-4.1.2-dev.so
cp glossa-interpreter/dist/Glossa.jar lib/Glossa.jar
cp glossa-interpreter/dist/lib/antlr-3.2.jar lib/antlr-3.2.jar
cp glossa-interpreter/dist/lib/jopt-simple-3.2.jar lib/jopt-simple-3.2.jar

rm -rf glossa-interpreter
rm -rf java-gnome
