#!/bin/bash

#*
#*  The MIT License
#* 
#*  Copyright 2012 Georgios Migdos <cyberpython@gmail.com>.
#* 
#*  Permission is hereby granted, free of charge, to any person obtaining a copy
#*  of this software and associated documentation files (the "Software"), to deal
#*  in the Software without restriction, including without limitation the rights
#*  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#*  copies of the Software, and to permit persons to whom the Software is
#*  furnished to do so, subject to the following conditions:
#* 
#*  The above copyright notice and this permission notice shall be included in
#*  all copies or substantial portions of the Software.
#* 
#*  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#*  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#*  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#*  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#*  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#*  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
#*  THE SOFTWARE.
#*

mkdir -p lib

if [ ! -f lib/gtk-4.1.jar ]
then

    if [ ! -d java-gnome ]
    then
        git clone git://github.com/cyberpython/java-gnome.git
    fi
    
    cd java-gnome

    ./configure

    make

    cd ../
    
    cp java-gnome/tmp/gtk-4.1.jar lib/gtk-4.1.jar
    cp java-gnome/tmp/libgtkjni-4.1.2-dev.so lib/libgtkjni-4.1.2-dev.so
fi

if [ ! -f lib/glossa-interpreter.jar ]
then
    
    if [ ! -d glossa-interpreter ]
    then
        git clone git://github.com/cyberpython/glossa-interpreter.git
    fi
    
    cd glossa-interpreter
    
    rm -rf build
    rm -rf dist

    ./build.sh

    cd ../
    
    cp glossa-interpreter/dist/glossa-interpreter.jar lib/glossa-interpreter.jar
    cp glossa-interpreter/dist/lib/antlr-3.2.jar lib/antlr-3.2.jar
    cp glossa-interpreter/dist/lib/jopt-simple-3.2.jar lib/jopt-simple-3.2.jar
fi

ant clean jar

mkdir -p dist
cp -R lib dist
jar umf manifest-libs dist/lingua.jar
